---
title: 'SFARI Genes (New scores)'
output:
  html_document:
    code_folding: 'hide'
---

```{r load_packages, echo=TRUE, warning=FALSE, message=FALSE}
#setwd('/afs/inf.ed.ac.uk/user/s17/s1725186/Documents/PhD-Models/FirstPUModel/RMarkdowns')

library(tidyverse) ; library(reshape2) ; library(glue) ; library(plotly) ; library(plotlyutils)
library(RColorBrewer) ; library(viridis) ; require(gridExtra) ; library(GGally)
library(Rtsne)
library(ClusterR)
library(DESeq2)
```

Load preprocessed dataset (preprocessing code in 19_10_14_data_preprocessing.Rmd)
```{r load_dataset, message=FALSE, warning=FALSE}
# Gandal dataset
load('./../Data/Gandal/preprocessed_data.RData')
datExpr = datExpr %>% data.frame
DE_info = DE_info %>% data.frame

# GO Neuronal annotations
GO_annotations = read.csv('./../../../PhD-InitialExperiments/FirstYearReview/Data/GO_annotations/genes_GO_annotations.csv')
GO_neuronal = GO_annotations %>% filter(grepl('neuron', go_term)) %>% 
              mutate('ID'=as.character(ensembl_gene_id)) %>% 
              dplyr::select(-ensembl_gene_id) %>% distinct(ID) %>%
              mutate('Neuronal'=1)

# SFARI Genes
SFARI_genes_new = read_csv('./../Data/SFARI/SFARI_genes_01-03-2020_with_ensembl_IDs.csv')
SFARI_genes_new = SFARI_genes_new[!duplicated(SFARI_genes_new$ID) & !is.na(SFARI_genes_new$ID),] %>%
                  mutate(`gene-score_new` = `gene-score`) %>%
                  dplyr::select(`gene-symbol`, `gene-name`, ID, `gene-score_new`)

SFARI_genes_old = read_csv('./../../../PhD-Models/FirstPUModel/Data/SFARI/SFARI_genes_08-29-2019_with_ensembl_IDs.csv')
SFARI_genes_old = SFARI_genes_old[!duplicated(SFARI_genes_old$ID) & !is.na(SFARI_genes_old$ID),] %>%
                  mutate(`gene-score_old` = `gene-score`) %>%
                  dplyr::select(ID, `gene-score_old`)

# Update DE_info with SFARI and Neuronal information
DE_info = DE_info %>% mutate('ID'=rownames(.)) %>% left_join(SFARI_genes_new, by='ID') %>%
  mutate(`gene-score_new`=ifelse(is.na(`gene-score_new`), 'None', `gene-score_new`)) %>%
  distinct(ID, .keep_all = TRUE) %>% left_join(GO_neuronal, by='ID') %>%
  mutate(Neuronal=ifelse(is.na(Neuronal), 0, Neuronal)) %>%
  mutate(gene.score.new=ifelse(`gene-score_new`=='None' & Neuronal==1, 'Neuronal', `gene-score_new`), significant=padj<0.05 & !is.na(padj)) %>%
  left_join(SFARI_genes_old, by='ID') %>%
  mutate(`gene-score_old`=ifelse(is.na(`gene-score_old`), 'None', `gene-score_old`)) %>%
  mutate(gene.score.old=ifelse(`gene-score_old`=='None' & Neuronal==1, 'Neuronal', `gene-score_old`), significant=padj<0.05 & !is.na(padj))
  


SFARI_colour_hue = function(r) {
  pal = c('#FF7631','#FFB100','#E8E328','#8CC83F','#62CCA6','#59B9C9','#b3b3b3','#808080','gray','#d9d9d9')[r]
}
```


# Boxplots de los dos scores uno junto al otro para compararlos