---
title: 'GO Enrichment Analysis'
output:
  html_document:
    code_folding: 'hide'
---

```{r load_packages, echo=TRUE, include=FALSE}
#setwd('/afs/inf.ed.ac.uk/user/s17/s1725186/Documents/PhD-InitialExperiments/FirstYearReview/Gandal/R_Markdowns')

library(tidyverse) ; library(plotly)
library(biomaRt)
library(topGO) ; library(GO.db) ; library(org.Mm.eg.db)
```

Load file with all the cluster memberships from the different methods explored
```{r}
clusterings = read.csv('./../Data/Gandal/clusters.csv', row.names=1)
```

### Exploratory analysis
```{r, fig.width=10}
plot_data = data.frame('Method'=factor(colnames(clusterings), levels = colnames(clusterings)), 
                       'No_cluster'=apply(clusterings,2,function(x) mean(x=='gray')),
                       'N_clusters'=apply(clusterings,2,function(x) length(unique(x))),
                       'Algorithm'=c(rep('Dynamic Tree',4), rep('Dynamic Hybrid',4)))

ggplotly(plot_data %>% ggplot(aes(Method, N_clusters, fill=Algorithm)) + geom_bar(stat='identity') + theme_minimal() + 
           theme(axis.text.x = element_text(angle=90))) %>% layout(legend = list(orientation = 'h', y=1.1))
```


```{r, fig.width=10}
plot_data = data.frame('Method' = factor(colnames(clusterings), levels = colnames(clusterings)),
                       'N_clusters'=apply(clusterings,2,function(x) length(unique(x))),
                       'cluster_size_mean'=rep(0,ncol(clusterings)),
                       'cluster_size_sd'=rep(0,ncol(clusterings)))

for(method in plot_data$Method){
  df = clusterings %>% filter(complete.cases(.)) %>% group_by_at(method) %>% tally
  plot_data[method,3:4] = c(mean(df$n), sd(df$n))
}

ggplotly(plot_data %>% ggplot(aes(cluster_size_mean, cluster_size_sd, color=N_clusters, id=Method)) + 
         geom_point() + theme_minimal() + xlab('Mean cluster size') + ylab('Cluster size SD') + labs(color = 'N Clusters'))

rm(method, df, plot_data)
```


## GO Enrichment Analysis following [this](https://datacatz.wordpress.com/2018/01/19/gene-set-enrichment-analysis-with-topgo-part-1/)

### Perform the Enrichment Analysis

```{r perform_EA, warning=FALSE, message=FALSE}
if(!file.exists('./../Data/Gandal/GO_EA_clusters.RData')){

  # Create map between gene IDs and GO IDs
  getinfo = c('ensembl_gene_id','external_gene_id','go_id')
  mart = useMart(biomart='ENSEMBL_MART_ENSEMBL', dataset='hsapiens_gene_ensembl', host='feb2014.archive.ensembl.org')
  ensembl2GO = getBM(attributes=getinfo, filters=c('ensembl_gene_id'), values=rownames(clusterings), mart=mart)
  ensembl2GO = ensembl2GO[ensembl2GO$go_id!='',]
  
  ensembl2gene = unique(ensembl2GO[,-3])[,2]
  names(ensembl2gene) = unique(ensembl2GO[,-3])[,1]
  
  
  EA_by_method = list()
  
  for(method in colnames(clusterings)){
    modules = clusterings[method]
    signif_terms_in_mods = list()
    
    for(module in unique(modules[!is.na(modules)])){
      
      # Create topGO object
      geneList = as.numeric(modules==module)
      geneList[is.na(geneList)] = 0
      names(geneList) = ensembl2gene[rownames(clusterings)]
      
      GOdata = new('topGOdata', ontology='BP', allGenes=geneList, geneSel=function(mod){return(mod==1)},
                   nodeSize=1, annot=annFUN.gene2GO, gene2GO=unstack(ensembl2GO[,c(3,2)]))
      
      # Perform statistical test
      weight_test = runTest(GOdata, algorithm = 'weight01', statistic = 'fisher')
      res = GenTable(GOdata, weightFisher = weight_test, orderBy = 'weightFisher',
                     ranksOf = 'weightFisher', topNodes = 1000) %>% 
            mutate(BH_corr = p.adjust(weightFisher, 'BH', n=length(unique(ensembl2GO$go_id))))
      
      if(sum(res$BH_corr<0.05, na.rm=TRUE)>0){
        signif_terms_in_mods[[as.character(module)]] = res[res$BH_corr<0.05,]
      }
    }
    
    EA_by_method[[method]] = signif_terms_in_mods
  }
  save(EA_by_method, file='./../Data/Gandal/GO_EA_clusters.RData')

} else {
  load('./../Data/Gandal/GO_DE_clusters.RData')
}
```


#### Results

```{r print_results}

for(method in names(EA_by_method)){
  cat(paste0('\n\nMethod ', method, ':'))
  print(paste0(EA_by_method[[method]] %>% length, ' Modules are significantly enriched'))
  
  for(i in 1:(EA_by_method[[method]] %>% length)){
    cat(paste0('\n\nGO terms enriched for module ', names(EA_by_method[[method]])[[i]],'\n'))
    print(EA_by_method[[method]][[i]][,c('GO.ID','Term','BH_corr')])
  }  
    
}
```
